import filmfortressImg from "@/public/filmfortress.jpeg";
import fakefriendsImg from "@/public/fakefriends.jpeg";
import petclinicImg from "@/public/aws-petclinic.png";

export const projectsData = [
  {
    title: "Spring-Petclinic-DevOps",
    description: {
      en: "The project focuses on implementing a CI/CD pipeline using Jenkins and ArgoCD, which hosts our application on a Kubernetes cluster in AWS EKS, as part of the DST Bootcamp.",
      de: "Das Projekt konzentriert sich auf die Implementierung einer CI/CD-Pipeline mithilfe von Jenkins und ArgoCD, die unsere Anwendung auf einem Kubernetes-Cluster in AWS EKS hostet, im Rahmen des DST Bootcamps.",
      es: "El proyecto se centra en la implementación de una pipeline CI/CD utilizando Jenkins y ArgoCD, que aloja nuestra aplicación en un clúster de Kubernetes en AWS EKS, como parte del Bootcamp en DST.",
    },
    tags: [
      "AWS",
      "Kubernetes",
      "Terraform",
      "Jenkins",
      "ArgoCD",
      "Prometheus",
      "Grafana",
    ],
    imageUrl: petclinicImg,
    githubUrl: "https://github.com/MatiasRoje/spring-petclinic-cloud",
    liveUrl: "https://github.com/MatiasRoje/spring-petclinic-cloud",
  },
  {
    title: "FilmFortress",
    description: {
      en: "Movie database website where users can explore and discover information about movies in an attractive way, as well as write reviews, rate movies, and add them to their watchlist.",
      de: "Film-Datenbank-Website, auf der Benutzer Informationen über Filme auf attraktive Weise erkunden und entdecken können. Außerdem können sie Bewertungen schreiben, Filme bewerten und sie ihrer Watchlist hinzufügen.",
      es: "Base de datos donde los usuarios pueden explorar y descubrir información sobre películas de una manera atractiva, así como escribir reseñas, calificar películas y agregarlas a su lista por ver.",
    },
    tags: [
      "TypeScript",
      "React",
      "Next.js",
      "MongoDB",
      "Tailwind",
      "React Query",
      "Next Auth",
    ],
    imageUrl: filmfortressImg,
    githubUrl: "https://github.com/MatiasRoje/FilmFortress2.0",
    liveUrl: "https://filmfortress.netlify.app/",
  },
  {
    title: "FakeFriends",
    description: {
      en: "FakeFriends was developed to help users get to know their friends better by asking personal questions and puzzles in an original way. Le Wagon Berlin Batch #1141 - Final Project.",
      de: "FakeFriends wurde entwickelt, um Benutzern dabei zu helfen, ihre Freunde besser kennenzulernen, indem sie auf originelle Weise persönliche Fragen und Rätsel stellen. Le Wagon Berlin Batch #1141 - Abschlussprojekt.",
      es: "FakeFriends fue desarrollado para ayudar a los usuarios a conocer mejor a sus amigos haciendo preguntas personales y rompecabezas de una manera original. Le Wagon Berlin Batch #1141 - Proyecto final.",
    },
    tags: [
      "Ruby on Rails",
      "HTML",
      "SASS",
      "Stimulus",
      "PostgreSQL",
      "Redis",
      "Animate.css",
    ],
    imageUrl: fakefriendsImg,
    githubUrl: "https://github.com/MatiasRoje/FakeFriends-MR",
    liveUrl: "https://fakefriends.onrender.com/",
  },
] as const;

export const skillsData = [
  "aws",
  "kubernetes",
  "docker",
  "terraform",
  "jenkins",
  "github",
  "gitlab",
  "py",
  "linux",
  "ansible",
  "prometheus",
  "grafana",
  "js",
  "ts",
  "react",
  "nextjs",
  "nodejs",
  "jquery",
  "html",
  "css",
  "sass",
  "tailwind",
  "ruby",
  "rails",
  "php",
  "mysql",
  "mongodb",
  "postgres",
  "postman",
  "git",
  "vscode",
] as const;
